#!/bin/env perl

##%%%#!/bin/perl
#======================================================================
# put this file in home directory or work directory. (~/.latexmkrc or WD/.latexmkrc)
# 1st : WD/.latexmkrc , if WD/.latexmkrc does not exist, load ~/.latexmkrc
# %O : option, %S : source file, %D : output file, $B : source file (non-extension)
#======================================================================
# $latex    = 'uplatex  %O -synctex=1 -halt-on-error -interaction=nonstopmode -file-line-error %S';
# $pdflatex = 'pdflatex %O -synctex=1 -halt-on-error -interaction=nonstopmode -file-line-error %S';
# # $lualatex = 'lualatex %O -synctex=1 -halt-on-error -interaction=nonstopmode -file-line-error %S';
$lualatex = 'lualatex %O -synctex=1 -halt-on-error -interaction=nonstopmode -file-line-error %S';
# #$xelatex  = 'xelatex  %O -synctex=1 -halt-on-error -interaction=nonstopmode -file-line-error %S';
# $biber = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B';
$biber = 'biber --bblencoding=utf8 -u -U --output_safechars';
##$bibtex = 'upbibtex %O %B';
# $makeindex = 'upmendex %O -o %D %S';
# #$makeindex = 'mendex %O -o %D %S';
# $dvipdf = 'dvipdfmx %O -o %D %S';
# $dvips = 'dvips %O -z -f %S | convbkmk -u > %D';
# $ps2pdf = 'ps2pdf %O %S %D';
# $pdf_mode                    = 3;
# $max_repeat                  = 5;
# $pvc_view_file_via_temporary = 0;
# # $pdf_previewer               = "evince";
# $pdf_previewer               = "zathura";
#======================================================================
#
#
#
# PDF-generating modes are:
# 1: pdflatex, as specified by $pdflatex variable (still largely in use)
# 2: postscript conversion, as specified by the $ps2pdf variable (useless)
# 3: dvi conversion, as specified by the $dvipdf variable (useless)
# 4: lualatex, as specified by the $lualatex variable (best)
# 5: xelatex, as specified by the $xelatex variable (second best)
$pdf_mode = 4;


$warnings_as_errors = 0;


# Show used CPU time. Looks like: https://tex.stackexchange.com/a/312224/120853
$show_time = 1;


# Default is 5; we seem to need more owed to the complexity of the document.
# Actual documents probably don't need this many since they won't use all features,
# plus won't be compiling from cold each time.
$max_repeat=4;



set_tex_cmds("--shell-escape --synctex=1 %O %S");





# option 2 is same as 1 (run biber when necessary), but also deletes the
# regeneratable bbl-file in a clenaup (`latexmk -c`). Do not use if original
# bib file is not available!
$bibtex_use = 2;  # default: 1

# Change default `biber` call, help catch errors faster/clearer. See
# https://web.archive.org/web/20200526101657/https://www.semipol.de/2018/06/12/latex-best-practices.html#database-entries
$biber = "biber --validate-datamodel %O %S";

# Keep the temporary files away from the tree
$out_dir = "./build";

ensure_path( 'TEXINPUTS', './include/' );




@default_files = qw(main.tex);
